# EEG Processing Configuration
eeg:
  sampling_rate: 250  # Hz
  channels: ["Fp1", "Fp2", "F7", "F3", "Fz", "F4", "F8", "T3", "C3", "Cz", "C4", "T4", "T5", "P3", "Pz", "P4", "T6", "O1", "O2"]
  notch_filter: 50  # Hz (power line frequency)
  bandpass_filter: [0.5, 45]  # Hz
  segment_length: 10  # seconds
  overlap: 0.5  # 50% overlap between segments

# Feature Extraction
features:
  time_domain:
    - mean
    - std
    - variance
    - skewness
    - kurtosis
    - zero_crossings
    - peak_to_peak
    - rms
    - entropy
  
  frequency_domain:
    - power_spectral_density
    - spectral_entropy
    - spectral_centroid
    - spectral_bandwidth
    - spectral_rolloff
    - spectral_flatness
  
  time_frequency:
    - wavelet_coefficients
    - spectrogram_features
  
  connectivity:
    - coherence
    - phase_locking_value
    - granger_causality

# Machine Learning Models
models:
  svm:
    kernel: "rbf"
    C: 1.0
    gamma: "scale"
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
  
  neural_network:
    layers: [128, 64, 32]
    dropout: 0.3
    activation: "relu"
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
  
  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8

# Training Configuration
training:
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  cv_folds: 5
  scoring: ["accuracy", "precision", "recall", "f1", "roc_auc"]
  
# Data Paths
paths:
  data_dir: "data/"
  models_dir: "models/"
  results_dir: "results/"
  plots_dir: "plots/"

# Visualization
visualization:
  style: "seaborn"
  figsize: [12, 8]
  dpi: 300
  save_format: "png" 